name: 'Ryu-Cho'
description: 'Automatic git commit tracking service.'

inputs:
  access-token:
    description: 'Access token for GitHub authentication'
    required: true
  username:
    description: 'Username for authenticated user'
    required: true
  email:
    description: 'Email for authenticated user'
    required: true
  upstream-repo:
    description: 'Repository that tracks the head repo. e.g. git@github.com:vuejs-jp/vite-docs-ja.git'
    required: true
  upstream-repo-branch:
    description: 'Branch name for upstream repo. Defaults to `main`'
    required: false
    default: 'main'
  head-repo:
    description: 'Repository to track. e.g. https://github.com/vitejs/vite'
    required: true
  head-repo-branch:
    description: 'Branch name for head repo. Defaults to `main`'
    required: false
    default: 'main'
  track-from:
    description: 'The git commit to track from. e.g. 4ed8b2f83a2f149734f3c5ecb6438309bd85a9e5'
    required: true
  path-starts-with:
    description: 'File path to track. e.g `docs/`'
    required: false
  workflow-name:
    description: 'GitHub workflow name that executes Ryu Cho action. Defaults to `ryu-cho`'
    required: false
    default: 'ryu-cho'

runs:
  using: "composite"
  steps:
    - name: Checkout Ryu-Cho
      run: ${{ github.action_path }}/scripts/checkout.sh
      shell: bash
    - name: Run Ryu-Cho
      env:
        ACCESS_TOKEN: ${{ inputs.access-token }}
        USER_NAME: ${{ inputs.username }}
        EMAIL: ${{ inputs.email }}
        UPSTREAM_REPO: ${{ inputs.upstream-repo }}
        UPSTREAM_REPO_BRANCH: ${{ inputs.upstream-repo-branch }}
        HEAD_REPO: ${{ inputs.head-repo }}
        HEAD_REPO_BRANCH: ${{ inputs.head-repo-branch }}
        TRACK_FROM: ${{ inputs.track-from }}
        PATH_STARTS_WITH: ${{ inputs.path-starts-with }}
        WORKFLOW_NAME: ${{ inputs.workflow-name }}
      run: |
        yarn install
        yarn start
      shell: bash
